export const screens = {
  MAIN_APP: 'MAIN_APP',

  SPLASH_MAIN: 'SPLASH_MAIN',

  AUTH_START: 'AUTH_START',
  AUTH_PHONE: 'AUTH_PHONE',
  AUTH_CODE: 'AUTH_CODE',
  AUTH_PROFILE: 'AUTH_PROFILE',

  tab: {
    TAB_CHATS: 'TAB_CHATS',
    TAB_CONTACTS: 'TAB_CONTACTS',
    TAB_STORIES: 'TAB_STORIES',
  },

  CHATS_MAIN: 'CHATS_MAIN',
  CHATS_DETAIL: 'CHATS_DETAIL',

  CONTACTS_MAIN: 'CONTACTS_MAIN',
  CONTACTS_CREATE: 'CONTACTS_CREATE',
  CONTACTS_DETAIL: 'CONTACTS_DETAIL',

  BROADCAST_CREATE: 'BROADCAST_CREATE',

  GROUPS_MAIN: 'GROUPS_MAIN',
  GROUPS_CREATE: 'GROUPS_CREATE',
  GROUPS_DETAIL: 'GROUPS_DETAIL',
  GROUPS_ADD_PARTICIPANTS: 'GROUPS_ADD_PARTICIPANTS',

  SETTINGS_MAIN: 'SETTINGS_MAIN',
};
